### PR TITLE
Refactor ItemDatabaseBuilder

### PR DESCRIPTION
**Pull request by StevenLiekens**
This is mostly just a code cleanup. I haven't really checked how fast this code is compared to what you have now.

See #22

Edit: it ought to be faster because I set `ServicePointManager.DefaultConnectionLimit` to the total number of pages (default value: 2).

### CODE REVIEW

**Comment by SamHurne** [comment]
Turns out this is actually slower.

Using the current implementation (```Parallel.For()```) = ```00:01:03```
Using the proposed interleaved tasks = ```00:01:53```

**Comment by StevenLiekens** [comment]
I think because not every task starts right away. I don't know how to change that.

**Comment by StevenLiekens** [comment]
I fixed the performance issues in my code. It should complete in under 30 seconds now.

**Comment by StevenLiekens** [comment]
I still think that it all comes down to the max number of requests that .NET / Windows allow you to make. It's super fast once you set `DefaultConnectionLimit` and `maxconnection` to `int.MaxValue`.

**Comment by SamHurne** [comment]
Wow, that does have a crazy impact. With that added:

Using the current implementation (```Parallel.For()```) = ```00:00:16```
Using the latest proposed interleaved tasks = ```00:00:10```

**Comment by SamHurne** [comment]
Any ideas as to why using several tasks instead of calling ```Parallel.For``` (or ```Parallel.Foreach```) is faster?

I like that your proposed implementation is faster, but I honestly found the code very hard to understand, even after reading the referenced link.

**Comment by StevenLiekens** [comment]
`Parallell.For` runs in smaller batches. The tasks created by `FindAllPagesAsync` all start immediately. That's over 200 HTTP requests that are all launched simultaneously.

The interleaving is there to iterate over tasks in the order that they complete instead of the order that they were started. This is necessary because some tasks can stall and block completed tasks that come after it.

**Comment by StevenLiekens** [comment]
Raising the max concurrent requests too high causes socket timeouts. Maybe the timeout can be increased, but that's probably not the best idea.

    2015-09-19 23:34:17.9727|ERROR|GW2PAO.API.Data.ItemsDatabaseBuilder|System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> GW2NET.Common.ServiceException: An error occurred while sending the request. See the inner exception for details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 64.25.47.16:443
       at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
       at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
       --- End of inner exception stack trace ---
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at GW2NET.Common.ServiceClient.<>c__DisplayClass8.<GetHttpWebResponseAsync>b__6(IAsyncResult ar)
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at GW2NET.Common.ServiceClient.<>c__DisplayClass3`1.<SendAsync>b__2(Task`1 task)
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at GW2NET.V2.Items.ItemRepository.ConvertAsyncResponse(Task`1 task, Int32 pageIndex)
       at GW2NET.V2.Items.ItemRepository.<>c__DisplayClass14.<GW2NET.Common.IPaginator<GW2NET.Items.Item>.FindPageAsync>b__13(Task`1 task)
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> GW2NET.Common.ServiceException: An error occurred while sending the request. See the inner exception for details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 64.25.47.16:443
       at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
       at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
       --- End of inner exception stack trace ---
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at GW2NET.Common.ServiceClient.<>c__DisplayClass8.<GetHttpWebResponseAsync>b__6(IAsyncResult ar)
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at GW2NET.Common.ServiceClient.<>c__DisplayClass3`1.<SendAsync>b__2(Task`1 task)
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at GW2NET.V2.Items.ItemRepository.ConvertAsyncResponse(Task`1 task, Int32 pageIndex)
       at GW2NET.V2.Items.ItemRepository.<>c__DisplayClass14.<GW2NET.Common.IPaginator<GW2NET.Items.Item>.FindPageAsync>b__13(Task`1 task)
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> GW2NET.Common.ServiceException: An error occurred while sending the request. See the inner exception for details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 64.25.47.16:443
       at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
       at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
       --- End of inner exception stack trace ---
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at GW2NET.Common.ServiceClient.<>c__DisplayClass8.<GetHttpWebResponseAsync>b__6(IAsyncResult ar)
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at GW2NET.Common.ServiceClient.<>c__DisplayClass3`1.<SendAsync>b__2(Task`1 task)
       at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    ---> (Inner Exception #0) GW2NET.Common.ServiceException: An error occurred while sending the request. See the inner exception for details. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 64.25.47.16:443
       at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
       at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
       --- End of inner exception stack trace ---
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at GW2NET.Common.ServiceClient.<>c__DisplayClass8.<GetHttpWebResponseAsync>b__6(IAsyncResult ar)
       --- End of inner exception stack trace ---<---
    <---
    <---

**Comment by SamHurne** [comment]
In my testing, even with it limited to 20, it only takes about 11 seconds to complete.

If I limit it to 8 (number of "cores" I have), I get similar performance to the Parallel.For(), so perhaps Parallel.For() limits it to the number of cores on the machine?

**Comment by SamHurne** [comment]
Awesome. Thanks for helping out with this!

**Comment by StevenLiekens** [comment]
I think the difference in `Parallel.For()` can be explained by how it batches the collection. If you give it a range of ints from 1 to 200 with the default degree of parallelism (number of "cores" == 8), it does something along these lines:

* Thread 1: page 1 to page 25
* Thread 2: page 26 to page 50
* Thread 3: page 51 to page 75
* Thread 4: page 76 to page 100
* Thread 5: page 101 to page 125
* Thread 6: page 126 to page 150
* Thread 7: page 151 to page 175
* Thread 8: page 176 to page 200

With this setup, the total running time is about as long as it takes for 25 tasks to complete (which should be about 16 seconds).

This is different than the code that creates and starts all 200 tasks at once, which is only limited by how the OS schedules and manages socket connections. In theory, the total running time should be the running time of the longest running task. In practice, Windows does not seem to be so great at scheduling that many concurrent connections. I also believe that the API does not allow that many concurrent connections from a single host, but I have no real evidence for that.

**Pull request merged**
